"""Write ``sample_prices.csv``: ten years of dated, SYNTHETIC daily prices.

The file exists so the audit command can be tried from a fresh clone with
no download. It is generated by the same process as the README study, with
a fixed seed, and stamped with weekday dates. It is not market data, and no
conclusion about any real instrument follows from an audit run on it.

    python examples/make_sample_prices.py
"""

from __future__ import annotations

import csv
from datetime import date, timedelta
from pathlib import Path

from honest_backtest import SyntheticConfig, generate_price_series

SEED = 20261005
OUT = Path(__file__).with_name("sample_prices.csv")


def weekdays(start: date, n: int) -> list[date]:
    """Return ``n`` consecutive weekdays from ``start``."""
    days: list[date] = []
    day = start
    while len(days) < n:
        if day.weekday() < 5:
            days.append(day)
        day += timedelta(days=1)
    return days


def main() -> None:
    """Generate the series and write it as a CSV."""
    series = generate_price_series(SyntheticConfig(n_bars=2520), seed=SEED)
    with OUT.open("w", newline="") as handle:
        writer = csv.writer(handle)
        writer.writerow(["date", "close", "volume"])
        for day, close, volume in zip(
            weekdays(date(2015, 1, 5), len(series)),
            series.closes,
            series.volumes,
            strict=True,
        ):
            writer.writerow([day.isoformat(), f"{close:.4f}", f"{volume:.0f}"])
    print(f"wrote {OUT} ({len(series)} rows)")


if __name__ == "__main__":
    main()
